### ISSUE TITLE
Paper 更改导致刷沙机失效

### ISSUE THREAD

**Issue by xb2016** [neko-craft/NekoAgent#1]
自 1.16.5#763 版本起，刷沙机的破解失效
https://github.com/PaperMC/Paper/commit/7d751ad8d33b85f2bb6b1cddc438b19418c01318

**Comment by ShirasawaSama** [comment]
确实 今天找了一天是哪改的都没找到

**Comment by xb2016** [comment]
这改动可太恶心了（）吓得我赶紧降级

**Comment by ShirasawaSama** [comment]
明天我再更新一下代码，直接把这行改了
https://github.com/PaperMC/Paper/commit/7d751ad8d33b85f2bb6b1cddc438b19418c01318#diff-cf1a5d3d0aa49b23e781994c37d675874176f2519320192b8a9437e2e3fee3b2R46

**Comment by xb2016** [comment]
可以 很暴力

**Comment by ShirasawaSama** [comment]
Fixed.

https://github.com/neko-craft/NekoAgent/commit/de3e6a624de4bf58f0e3c7a48e1e5f3681f7b0ec
