### ISSUE TITLE
关于1.16的功能缺失

### ISSUE THREAD

**Issue by g2nnyS** [neko-craft/NekoAgent#2]
请问1.16是否也能添加1.17中的特性（比如:/mspt,潜影贝重生）呢？

**Comment by g2nnyS** [comment]
> 请问1.16是否也能添加1.17中的特性（比如:/mspt,潜影贝重生）呢？

现在仍然有许多服务器停留在1.16（包括我的）我想我们需要他

**Comment by ShirasawaSama** [comment]
不考虑，因为1.16和1.17 mc代码结构变化比较大，如有需求请更新1.17

而且1.16服务端也可以直接更新到1.17，没有什么不兼容的问题
